language: python

cache:
  - pip: true
  - directories:
      - $HOME/.cache/pypoetry

python:
  - 3.6
  - 3.7

matrix:
  include:
    - name: "Python: 3.6"
      os: osx
      language: shell
      python: 3.6
      cache:
        - directories:
          - $HOME/Library/Caches/pip
          - $HOME/Library/Caches/pypoetry
    - name: "Python: 3.7"
      os: osx
      language: shell
      python: 3.7
      cache:
        - directories:
          - $HOME/Library/Caches/pip
          - $HOME/Library/Caches/pypoetry
    - name: "Python: 3.6"
      os: windows
      language: shell
      before_install:
        - choco install python --version=3.6.8
        - choco install make
        - python -m pip install -U pip setuptools
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      cache:
        directories:
          - $LOCALAPPDATA/pip/Cache
          - $LOCALAPPDATA/pypoetry/cache
    - name: "Python: 3.7"
      os: windows
      language: shell
      before_install:
        - choco install python --version=3.7.7
        - choco install make
        - python -m pip install -U pip setuptools
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      cache:
        directories:
          - $LOCALAPPDATA/pip/Cache
          - $LOCALAPPDATA/pypoetry/cache

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - make install

script:
  - make test

after_success:
  - poetry run codecov

before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi $TEST_PYPI_USER $TEST_PYPI_PASS
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build

deploy:
  - provider: script
    script: poetry publish -r testpypi
    skip_cleanup: true
    on:
      branch: develop
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME == "linux"
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME == "linux"